import { Preset } from './types';

export const BASE_PRESETS: Preset[] = [
  {
    name: "Master Flow",
    masterAmount: 1.0,
    motionAmount: 0.6,
    spaceBreath: 0.5,
    airShimmer: 0.4,
    safetyLimit: -1.0,
    dramaticMode: false,
    dramaticAmount: 0.5,
    low: { gain: 1.2, drive: 0.1, filterCutoff: 200 },
    mid: { gain: 1.0, drive: 0.05, filterCutoff: 2000 },
    high: { gain: 1.1, drive: 0.1, filterCutoff: 8000 },
    space: { mix: 0.3, irType: "Air", delayTime: 0.2, delayFeedback: 0.2 },
  },
  {
    name: "Heavy Breath",
    masterAmount: 1.2,
    motionAmount: 0.9,
    spaceBreath: 0.8,
    airShimmer: 0.2,
    safetyLimit: -0.5,
    dramaticMode: false,
    dramaticAmount: 0.5,
    low: { gain: 1.4, drive: 0.2, filterCutoff: 180 },
    mid: { gain: 0.9, drive: 0.1, filterCutoff: 1200 },
    high: { gain: 0.9, drive: 0.1, filterCutoff: 7000 },
    space: { mix: 0.4, irType: "Tight", delayTime: 0.1, delayFeedback: 0.1 },
  },
  {
    name: "Lush & Open",
    masterAmount: 0.9,
    motionAmount: 0.4,
    spaceBreath: 0.9,
    airShimmer: 0.8,
    safetyLimit: -1.5,
    dramaticMode: false,
    dramaticAmount: 0.5,
    low: { gain: 1.0, drive: 0.05, filterCutoff: 150 },
    mid: { gain: 0.8, drive: 0.05, filterCutoff: 3000 },
    high: { gain: 1.3, drive: 0.1, filterCutoff: 10000 },
    space: { mix: 0.6, irType: "Cathedral", delayTime: 0.4, delayFeedback: 0.4 },
  },
  {
    name: "Dramatic Pulse",
    masterAmount: 1.0,
    motionAmount: 1.0,
    spaceBreath: 1.0,
    airShimmer: 1.0,
    safetyLimit: -1.0,
    dramaticMode: true,
    dramaticAmount: 1.0,
    low: { gain: 1.0, drive: 0.3, filterCutoff: 200 },
    mid: { gain: 1.0, drive: 0.2, filterCutoff: 2000 },
    high: { gain: 1.0, drive: 0.2, filterCutoff: 8000 },
    space: { mix: 0.5, irType: "Wide", delayTime: 0.3, delayFeedback: 0.5 },
  }
];
